schemaVersion: "2.0.0"

commandTests:
  - name: "Blackfire Module Loaded"
    command: "php-fpm"
    args: ["-m"]
    expectedOutput:
      - "(?m)^blackfire"
  - name: "Blackfire Configured"
    command: "php-fpm"
    args: ["-i"]
    expectedOutput:
      - "(?m)^\\s+with blackfire"
      - "(?m)^blackfire\\.agent_socket => tcp://blackfire-agent:8707 => tcp://blackfire-agent:8707"
      - "(?m)^blackfire\\.apm_enabled => 1 => 1"

fileExistenceTests:
  - name: "Blackfire Configuration File Exists"
    path: "/etc/php.d/zz-blackfire.ini"
    shouldExist: true
  - name: "Blackfire CLI Exists"
    path: "/usr/bin/blackfire"
    shouldExist: true